### ISSUE TITLE
Create `get_video_miniature` function

### ISSUE THREAD

**Issue by Pabloo22** [Pabloo22/ask-youtube-playlists#17]
Create a function that given a url returns an object that can be send to [st.image](https://docs.streamlit.io/library/api-reference/media/st.image) to show the miniature of the video.

Including this object inside the document metadata could increase significantly the size of the data (unless the object is another url, but even in this case, this approach should be equally good at least).

The function should be cached. We can use the decorator `@st.cache_data` for this.

**Comment by alvarola17** [comment]
Added inside the create_chunked_data function
